<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ImportInvoiceDetailsDatabase extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table('ImportInvoiceDetails')->insert(
            [
                [
                    'imp_id' => 1,
                    'prd_id' => 1,
                    'imp_quantity' => 10,
                    'imp_price' => 40000,
                    'imp_expiryDate' => '2022/12/01',
                    'prd_status_id' => 3,
                    'imp_quantity_left' => 5,
                ],
                [
                    'imp_id' => 1,
                    'prd_id' => 2,
                    'imp_quantity' => 10,
                    'imp_price' => 20000,
                    'imp_expiryDate' => '2022/12/02',
                    'prd_status_id' => 3,
                    'imp_quantity_left' => 5,
                ],
                [
                    'imp_id' => 1,
                    'prd_id' => 7,
                    'imp_quantity' => 50,
                    'imp_price' => 10000,
                    'imp_expiryDate' => '2023/12/07',
                    'prd_status_id' => 1,
                    'imp_quantity_left' => 45,
                ],
                [
                    'imp_id' => 1,
                    'prd_id' => 8,
                    'imp_quantity' => 45,
                    'imp_price' => 18000,
                    'imp_expiryDate' => '2023/12/08',
                    'prd_status_id' => 1,
                    'imp_quantity_left' => 40,
                ],
                [
                    'imp_id' => 2,
                    'prd_id' => 3,
                    'imp_quantity' => 10,
                    'imp_price' => 8000,
                    'imp_expiryDate' => '2022/12/03',
                    'prd_status_id' => 3,
                    'imp_quantity_left' => 5,
                ],
                [
                    'imp_id' => 2,
                    'prd_id' => 4,
                    'imp_quantity' => 10,
                    'imp_price' => 25000,
                    'imp_expiryDate' => '2022/12/04',
                    'prd_status_id' => 3,
                    'imp_quantity_left' => 5,
                ],
                [
                    'imp_id' => 2,
                    'prd_id' => 12,
                    'imp_quantity' => 250,
                    'imp_price' => 50000,
                    'imp_expiryDate' => '2023/12/12',
                    'prd_status_id' => 1,
                    'imp_quantity_left' => 245,
                ],
                [
                    'imp_id' => 2,
                    'prd_id' => 13,
                    'imp_quantity' => 200,
                    'imp_price' => 65000,
                    'imp_expiryDate' => '2023/12/13',
                    'prd_status_id' => 1,
                    'imp_quantity_left' => 195,
                ],
                [
                    'imp_id' => 3,
                    'prd_id' => 5,
                    'imp_quantity' => 5,
                    'imp_price' => 12000,
                    'imp_expiryDate' => '2022/12/05',
                    'prd_status_id' => 4,
                    'imp_quantity_left' => 0,
                ],
                [
                    'imp_id' => 3,
                    'prd_id' => 6,
                    'imp_quantity' => 5,
                    'imp_price' => 50000,
                    'imp_expiryDate' => '2022/12/06',
                    'prd_status_id' => 4,
                    'imp_quantity_left' => 0,
                ],
                [
                    'imp_id' => 3,
                    'prd_id' => 9,
                    'imp_quantity' => 15,
                    'imp_price' => 90000,
                    'imp_expiryDate' => '2023/12/09',
                    'prd_status_id' => 1,
                    'imp_quantity_left' => 10,
                ],
                [
                    'imp_id' => 3,
                    'prd_id' => 10,
                    'imp_quantity' => 50,
                    'imp_price' => 10000,
                    'imp_expiryDate' => '2023/12/10',
                    'prd_status_id' => 1,
                    'imp_quantity_left' => 45,
                ],
                [
                    'imp_id' => 3,
                    'prd_id' => 11,
                    'imp_quantity' => 50,
                    'imp_price' => 10000,
                    'imp_expiryDate' => '2023/12/11',
                    'prd_status_id' => 1,
                    'imp_quantity_left' => 45,
                ],
                [
                    'imp_id' => 4,
                    'prd_id' => 1,
                    'imp_quantity' => 80,
                    'imp_price' => 40000,
                    'imp_expiryDate' => '2023/12/01',
                    'prd_status_id' => 1,
                    'imp_quantity_left' => 75,
                ],
                [
                    'imp_id' => 4,
                    'prd_id' => 2,
                    'imp_quantity' => 100,
                    'imp_price' => 20000,
                    'imp_expiryDate' => '2023/12/02',
                    'prd_status_id' => 1,
                    'imp_quantity_left' => 95,
                ],
                [
                    'imp_id' => 5,
                    'prd_id' => 3,
                    'imp_quantity' => 80,
                    'imp_price' => 8000,
                    'imp_expiryDate' => '2023/12/03',
                    'prd_status_id' => 1,
                    'imp_quantity_left' => 75,
                ],
                [
                    'imp_id' => 5,
                    'prd_id' => 4,
                    'imp_quantity' => 100,
                    'imp_price' => 25000,
                    'imp_expiryDate' => '2023/12/04',
                    'prd_status_id' => 1,
                    'imp_quantity_left' => 95,
                ],
                [
                    'imp_id' => 6,
                    'prd_id' => 5,
                    'imp_quantity' => 35,
                    'imp_price' => 12000,
                    'imp_expiryDate' => '2023/12/05',
                    'prd_status_id' => 1,
                    'imp_quantity_left' => 30,
                ],
                [
                    'imp_id' => 6,
                    'prd_id' => 6,
                    'imp_quantity' => 100,
                    'imp_price' => 50000,
                    'imp_expiryDate' => '2023/12/06',
                    'prd_status_id' => 1,
                    'imp_quantity_left' => 100,
                ],
                [
                    'imp_id' => 7,
                    'prd_id' => 3,
                    'imp_quantity' => 80,
                    'imp_price' => 9000,
                    'imp_expiryDate' => '2024/12/06',
                    'prd_status_id' => 1,
                    'imp_quantity_left' => 80,
                ],
                [
                    'imp_id' => 7,
                    'prd_id' => 10,
                    'imp_quantity' => 200,
                    'imp_price' => 9000,
                    'imp_expiryDate' => '2025/02/06',
                    'prd_status_id' => 1,
                    'imp_quantity_left' => 200,
                ],
                [
                    'imp_id' => 7,
                    'prd_id' => 16,
                    'imp_quantity' => 100,
                    'imp_price' => 25000,
                    'imp_expiryDate' => '2025/01/01',
                    'prd_status_id' => 1,
                    'imp_quantity_left' => 100,
                ],
                [
                    'imp_id' => 8,
                    'prd_id' => 15,
                    'imp_quantity' => 100,
                    'imp_price' => 19000,
                    'imp_expiryDate' => '2025/01/01',
                    'prd_status_id' => 1,
                    'imp_quantity_left' => 100,
                ],
                [
                    'imp_id' => 9,
                    'prd_id' => 4,
                    'imp_quantity' => 100,
                    'imp_price' => 29000,
                    'imp_expiryDate' => '2024/03/01',
                    'prd_status_id' => 1,
                    'imp_quantity_left' => 100,
                ],
                [
                    'imp_id' => 9,
                    'prd_id' => 17,
                    'imp_quantity' => 180,
                    'imp_price' => 35000,
                    'imp_expiryDate' => '2024/03/01',
                    'prd_status_id' => 1,
                    'imp_quantity_left' => 180,
                ],
                [
                    'imp_id' => 10,
                    'prd_id' => 14,
                    'imp_quantity' => 200,
                    'imp_price' => 50000,
                    'imp_expiryDate' => '2024/10/01',
                    'prd_status_id' => 1,
                    'imp_quantity_left' => 200,
                ],
                [
                    'imp_id' => 10,
                    'prd_id' => 17,
                    'imp_quantity' => 100,
                    'imp_price' => 35000,
                    'imp_expiryDate' => '2024/03/01',
                    'prd_status_id' => 1,
                    'imp_quantity_left' => 100,
                ],
                [
                    'imp_id' => 11,
                    'prd_id' => 18,
                    'imp_quantity' => 40,
                    'imp_price' => 55000,
                    'imp_expiryDate' => '2024/01/01',
                    'prd_status_id' => 1,
                    'imp_quantity_left' => 40,
                ],
                [
                    'imp_id' => 12,
                    'prd_id' => 19,
                    'imp_quantity' => 50,
                    'imp_price' => 50000,
                    'imp_expiryDate' => '2023/12/01',
                    'prd_status_id' => 1,
                    'imp_quantity_left' => 45,
                ],
                [
                    'imp_id' => 13,
                    'prd_id' => 20,
                    'imp_quantity' => 30,
                    'imp_price' => 120000,
                    'imp_expiryDate' => '2024/12/30',
                    'prd_status_id' => 1,
                    'imp_quantity_left' => 30,
                ],
            ]
        );
    }
}
