<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SalesInvoicesDatabase extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table('SalesInvoices')->insert(
            [
                [
                    'use_id' => 5,
                    'sal_date' => '2022/01/15',
                    'sal_total' => 475000,
                    'ship_id' => 1,
                    'sal_province' => 'Hà Nội',
                    'sal_district' => 'Hoàng Mai',
                    'sal_town' => 'Đại Kim',
                    'sal_detailAddress' => 'Nhà 1',
                    'sal_status_id' => 4,
                ],
                [
                    'use_id' => 6,
                    'sal_date' => '2022/02/01',
                    'sal_total' => 250000,
                    'ship_id' => 1,
                    'sal_province' => 'Hà Nội',
                    'sal_district' => 'Hoàng Mai',
                    'sal_town' => 'Đại Kim',
                    'sal_detailAddress' => 'Nhà 1',
                    'sal_status_id' => 4,
                ],
                [
                    'use_id' => 7,
                    'sal_date' => '2022/03/01',
                    'sal_total' => 100000,
                    'ship_id' => 1,
                    'sal_province' => 'Hà Nội',
                    'sal_district' => 'Hoàng Mai',
                    'sal_town' => 'Đại Kim',
                    'sal_detailAddress' => 'Nhà 1',
                    'sal_status_id' => 4,
                ],
                [
                    'use_id' => 5,
                    'sal_date' => '2022/04/01',
                    'sal_total' => 300000,
                    'ship_id' => 1,
                    'sal_province' => 'Hà Nội',
                    'sal_district' => 'Hoàng Mai',
                    'sal_town' => 'Đại Kim',
                    'sal_detailAddress' => 'Nhà 1',
                    'sal_status_id' => 4,
                ],
                [
                    'use_id' => 6,
                    'sal_date' => '2022/05/01',
                    'sal_total' => 150000,
                    'ship_id' => 1,
                    'sal_province' => 'Hà Nội',
                    'sal_district' => 'Hoàng Mai',
                    'sal_town' => 'Đại Kim',
                    'sal_detailAddress' => 'Nhà 1',
                    'sal_status_id' => 4,
                ],
                [
                    'use_id' => 7,
                    'sal_date' => '2022/06/01',
                    'sal_total' => 480000,
                    'ship_id' => 1,
                    'sal_province' => 'Hà Nội',
                    'sal_district' => 'Hoàng Mai',
                    'sal_town' => 'Đại Kim',
                    'sal_detailAddress' => 'Nhà 1',
                    'sal_status_id' => 4,
                ],
                [
                    'use_id' => 5,
                    'sal_date' => '2022/07/01',
                    'sal_total' => 100000,
                    'ship_id' => 1,
                    'sal_province' => 'Hà Nội',
                    'sal_district' => 'Hoàng Mai',
                    'sal_town' => 'Đại Kim',
                    'sal_detailAddress' => 'Nhà 1',
                    'sal_status_id' => 4,
                ],
                [
                    'use_id' => 6,
                    'sal_date' => '2022/08/01',
                    'sal_total' => 155000,
                    'ship_id' => 1,
                    'sal_province' => 'Hà Nội',
                    'sal_district' => 'Hoàng Mai',
                    'sal_town' => 'Đại Kim',
                    'sal_detailAddress' => 'Nhà 1',
                    'sal_status_id' => 4,
                ],
                [
                    'use_id' => 7,
                    'sal_date' => '2022/09/01',
                    'sal_total' => 675000,
                    'ship_id' => 1,
                    'sal_province' => 'Hà Nội',
                    'sal_district' => 'Hoàng Mai',
                    'sal_town' => 'Đại Kim',
                    'sal_detailAddress' => 'Nhà 1',
                    'sal_status_id' => 4,
                ],
                [
                    'use_id' => 5,
                    'sal_date' => '2022/10/01',
                    'sal_total' => 100000,
                    'ship_id' => 1,
                    'sal_province' => 'Hà Nội',
                    'sal_district' => 'Hoàng Mai',
                    'sal_town' => 'Đại Kim',
                    'sal_detailAddress' => 'Nhà 1',
                    'sal_status_id' => 4,
                ],
                [
                    'use_id' => 6,
                    'sal_date' => '2022/11/01',
                    'sal_total' => 100000,
                    'ship_id' => 1,
                    'sal_province' => 'Hà Nội',
                    'sal_district' => 'Hoàng Mai',
                    'sal_town' => 'Đại Kim',
                    'sal_detailAddress' => 'Nhà 1',
                    'sal_status_id' => 4,
                ],
                [
                    'use_id' => 7,
                    'sal_date' => '2022/12/01',
                    'sal_total' => 425000,
                    'ship_id' => 1,
                    'sal_province' => 'Hà Nội',
                    'sal_district' => 'Hoàng Mai',
                    'sal_town' => 'Đại Kim',
                    'sal_detailAddress' => 'Nhà 1',
                    'sal_status_id' => 4,
                ],
                [
                    'use_id' => 5,
                    'sal_date' => '2023/01/17',
                    'sal_total' => 525000,
                    'ship_id' => 1,
                    'sal_province' => 'Hà Nội',
                    'sal_district' => 'Hoàng Mai',
                    'sal_town' => 'Đại Kim',
                    'sal_detailAddress' => 'Nhà 1',
                    'sal_status_id' => 4,
                ],
                [
                    'use_id' => 6,
                    'sal_date' => '2023/02/01',
                    'sal_total' => 200000,
                    'ship_id' => 1,
                    'sal_province' => 'Hà Nội',
                    'sal_district' => 'Hoàng Mai',
                    'sal_town' => 'Đại Kim',
                    'sal_detailAddress' => 'Nhà 1',
                    'sal_status_id' => 4,
                ],
                [
                    'use_id' => 7,
                    'sal_date' => '2023/03/01',
                    'sal_total' => 250000,
                    'ship_id' => 1,
                    'sal_province' => 'Hà Nội',
                    'sal_district' => 'Hoàng Mai',
                    'sal_town' => 'Đại Kim',
                    'sal_detailAddress' => 'Nhà 1',
                    'sal_status_id' => 4,
                ],
                [
                    'use_id' => 5,
                    'sal_date' => '2023/04/01',
                    'sal_total' => 100000,
                    'ship_id' => 1,
                    'sal_province' => 'Hà Nội',
                    'sal_district' => 'Hoàng Mai',
                    'sal_town' => 'Đại Kim',
                    'sal_detailAddress' => 'Nhà 1',
                    'sal_status_id' => 4,
                ],
                [
                    'use_id' => 6,
                    'sal_date' => '2023/05/01',
                    'sal_total' => 300000,
                    'ship_id' => 1,
                    'sal_province' => 'Hà Nội',
                    'sal_district' => 'Hoàng Mai',
                    'sal_town' => 'Đại Kim',
                    'sal_detailAddress' => 'Nhà 1',
                    'sal_status_id' => 4,
                ],
                [
                    'use_id' => 7,
                    'sal_date' => '2023/06/01',
                    'sal_total' => 150000,
                    'ship_id' => 1,
                    'sal_province' => 'Hà Nội',
                    'sal_district' => 'Hoàng Mai',
                    'sal_town' => 'Đại Kim',
                    'sal_detailAddress' => 'Nhà 1',
                    'sal_status_id' => 4,
                ],
                [
                    'use_id' => 7,
                    'sal_date' => '2023/07/01',
                    'sal_total' => 485000,
                    'ship_id' => 1,
                    'sal_province' => 'Hà Nội',
                    'sal_district' => 'Hoàn Kiếm',
                    'sal_town' => 'Hàng Trống',
                    'sal_detailAddress' => 'Nhà 10 Ngõ 5 Phố Hàng Trống',
                    'sal_status_id' => 2,
                ],
                [
                    'use_id' => 8,
                    'sal_date' => '2023/07/02',
                    'sal_total' => 100000,
                    'ship_id' => 3,
                    'sal_province' => 'Quảng Ninh',
                    'sal_district' => 'Hạ Long',
                    'sal_town' => 'Bãi Cháy',
                    'sal_detailAddress' => 'Nhà 10 Ngõ 5',
                    'sal_status_id' => 2,
                ],
                [
                    'use_id' => 8,
                    'sal_date' => '2023/07/15',
                    'sal_total' => 520000,
                    'ship_id' => 2,
                    'sal_province' => 'Quảng Ninh',
                    'sal_district' => 'Hạ Long',
                    'sal_town' => 'Bãi Cháy',
                    'sal_detailAddress' => 'Nhà 10 Ngõ 5',
                    'sal_status_id' => 2,
                ],
            ]
        );
    }
}
