<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SalesInvoicesDatabase extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table('SalesInvoices')->insert(
            [
                [
                    'use_id' => 5,
                    'sal_date' => '2022/01/15',
                    'sal_total' => 475000,
                    'ship_id' => 1,
                    'sal_province' => 'Hà Nội',
                    'sal_district' => 'Hoàng Mai',
                    'sal_town' => 'Đại Kim',
                    'sal_detailAddress' => 'Số 1 Đại Kim',
                    'sal_status_id' => 4,
                ],
                [
                    'use_id' => 6,
                    'sal_date' => '2022/02/01',
                    'sal_total' => 250000,
                    'ship_id' => 1,
                    'sal_province' => 'Hà Nội',
                    'sal_district' => 'Hoàng Mai',
                    'sal_town' => 'Đại Kim',
                    'sal_detailAddress' => '59 Nghiêm Xuân Yêm',
                    'sal_status_id' => 4,
                ],
                [
                    'use_id' => 7,
                    'sal_date' => '2022/03/01',
                    'sal_total' => 100000,
                    'ship_id' => 1,
                    'sal_province' => 'Hà Nội',
                    'sal_district' => 'Hoàng Mai',
                    'sal_town' => 'Đại Kim',
                    'sal_detailAddress' => 'Số 12 Ngõ 354 Kim Giang',
                    'sal_status_id' => 4,
                ],
                [
                    'use_id' => 5,
                    'sal_date' => '2022/04/01',
                    'sal_total' => 300000,
                    'ship_id' => 1,
                    'sal_province' => 'Hà Nội',
                    'sal_district' => 'Hoàng Mai',
                    'sal_town' => 'Đại Kim',
                    'sal_detailAddress' => '365 Kim Giang',
                    'sal_status_id' => 4,
                ],
                [
                    'use_id' => 6,
                    'sal_date' => '2022/05/01',
                    'sal_total' => 150000,
                    'ship_id' => 1,
                    'sal_province' => 'Hà Nội',
                    'sal_district' => 'Hoàng Mai',
                    'sal_town' => 'Đại Kim',
                    'sal_detailAddress' => '59 Nghiêm Xuân Yêm',
                    'sal_status_id' => 4,
                ],
                [
                    'use_id' => 7,
                    'sal_date' => '2022/05/01',
                    'sal_total' => 480000,
                    'ship_id' => 1,
                    'sal_province' => 'Hà Nội',
                    'sal_district' => 'Hoàng Mai',
                    'sal_town' => 'Đại Kim',
                    'sal_detailAddress' => 'Số 12 Ngõ 354 Kim Giang',
                    'sal_status_id' => 4,
                ],
                [
                    'use_id' => 5,
                    'sal_date' => '2022/06/01',
                    'sal_total' => 100000,
                    'ship_id' => 1,
                    'sal_province' => 'Hà Nội',
                    'sal_district' => 'Hoàng Mai',
                    'sal_town' => 'Đại Kim',
                    'sal_detailAddress' => '365 Kim Giang',
                    'sal_status_id' => 4,
                ],
                [
                    'use_id' => 6,
                    'sal_date' => '2022/06/10',
                    'sal_total' => 155000,
                    'ship_id' => 1,
                    'sal_province' => 'Hà Nội',
                    'sal_district' => 'Hoàng Mai',
                    'sal_town' => 'Đại Kim',
                    'sal_detailAddress' => '59 Nghiêm Xuân Yêm',
                    'sal_status_id' => 4,
                ],
                [
                    'use_id' => 7,
                    'sal_date' => '2022/07/01',
                    'sal_total' => 675000,
                    'ship_id' => 1,
                    'sal_province' => 'Hà Nội',
                    'sal_district' => 'Hoàng Mai',
                    'sal_town' => 'Đại Kim',
                    'sal_detailAddress' => 'Số 12 Ngõ 354 Kim Giang',
                    'sal_status_id' => 4,
                ],
                [
                    'use_id' => 5,
                    'sal_date' => '2022/08/01',
                    'sal_total' => 100000,
                    'ship_id' => 1,
                    'sal_province' => 'Hà Nội',
                    'sal_district' => 'Hoàng Mai',
                    'sal_town' => 'Đại Kim',
                    'sal_detailAddress' => '365 Kim Giang',
                    'sal_status_id' => 4,
                ],
                [
                    'use_id' => 6,
                    'sal_date' => '2022/08/12',
                    'sal_total' => 100000,
                    'ship_id' => 1,
                    'sal_province' => 'Hà Nội',
                    'sal_district' => 'Hoàng Mai',
                    'sal_town' => 'Đại Kim',
                    'sal_detailAddress' => '59 Nghiêm Xuân Yêm',
                    'sal_status_id' => 4,
                ],
                [
                    'use_id' => 7,
                    'sal_date' => '2022/09/01',
                    'sal_total' => 425000,
                    'ship_id' => 1,
                    'sal_province' => 'Hà Nội',
                    'sal_district' => 'Hoàng Mai',
                    'sal_town' => 'Đại Kim',
                    'sal_detailAddress' => 'Số 12 Ngõ 354 Kim Giang',
                    'sal_status_id' => 4,
                ],
                [
                    'use_id' => 5,
                    'sal_date' => '2022/10/17',
                    'sal_total' => 525000,
                    'ship_id' => 1,
                    'sal_province' => 'Hà Nội',
                    'sal_district' => 'Hoàng Mai',
                    'sal_town' => 'Đại Kim',
                    'sal_detailAddress' => 'Số 50 Nguyễn Xiển',
                    'sal_status_id' => 4,
                ],
                [
                    'use_id' => 6,
                    'sal_date' => '2022/10/01',
                    'sal_total' => 200000,
                    'ship_id' => 1,
                    'sal_province' => 'Hà Nội',
                    'sal_district' => 'Hoàng Mai',
                    'sal_town' => 'Đại Kim',
                    'sal_detailAddress' => '59 Nghiêm Xuân Yêm',
                    'sal_status_id' => 4,
                ],
                [
                    'use_id' => 7,
                    'sal_date' => '2022/11/01',
                    'sal_total' => 250000,
                    'ship_id' => 1,
                    'sal_province' => 'Hà Nội',
                    'sal_district' => 'Hoàng Mai',
                    'sal_town' => 'Đại Kim',
                    'sal_detailAddress' => 'Số 50 Nguyễn Xiển',
                    'sal_status_id' => 4,
                ],
                [
                    'use_id' => 5,
                    'sal_date' => '2022/11/01',
                    'sal_total' => 100000,
                    'ship_id' => 1,
                    'sal_province' => 'Hà Nội',
                    'sal_district' => 'Hoàng Mai',
                    'sal_town' => 'Đại Kim',
                    'sal_detailAddress' => '212 Kim Giang',
                    'sal_status_id' => 4,
                ],
                [
                    'use_id' => 6,
                    'sal_date' => '2022/11/14',
                    'sal_total' => 300000,
                    'ship_id' => 1,
                    'sal_province' => 'Hà Nội',
                    'sal_district' => 'Hoàng Mai',
                    'sal_town' => 'Đại Kim',
                    'sal_detailAddress' => 'Số 50 Nguyễn Xiển',
                    'sal_status_id' => 4,
                ],
                [
                    'use_id' => 7,
                    'sal_date' => '2022/12/01',
                    'sal_total' => 150000,
                    'ship_id' => 1,
                    'sal_province' => 'Hà Nội',
                    'sal_district' => 'Hoàng Mai',
                    'sal_town' => 'Đại Kim',
                    'sal_detailAddress' => 'Số 50 Nguyễn Xiển',
                    'sal_status_id' => 4,
                ],
                [
                    'use_id' => 7,
                    'sal_date' => '2022/12/25',
                    'sal_total' => 485000,
                    'ship_id' => 1,
                    'sal_province' => 'Hà Nội',
                    'sal_district' => 'Hoàn Kiếm',
                    'sal_town' => 'Hàng Trống',
                    'sal_detailAddress' => 'Số 29 Phố Hàng Trống',
                    'sal_status_id' => 4,
                ],
                [
                    'use_id' => 8,
                    'sal_date' => '2022/12/26',
                    'sal_total' => 122000,
                    'ship_id' => 2,
                    'sal_province' => 'Quảng Ninh',
                    'sal_district' => 'Hạ Long',
                    'sal_town' => 'Bãi Cháy',
                    'sal_detailAddress' => 'Số 5 đường Bãi Cháy',
                    'sal_status_id' => 2,
                ],
                [
                    'use_id' => 8,
                    'sal_date' => '2023/01/15',
                    'sal_total' => 542000,
                    'ship_id' => 2,
                    'sal_province' => 'Quảng Ninh',
                    'sal_district' => 'Hạ Long',
                    'sal_town' => 'Bãi Cháy',
                    'sal_detailAddress' => 'Số 5 đường Bãi Cháy',
                    'sal_status_id' => 4,
                ],
                [
                    'use_id' => 7,
                    'sal_date' => '2023/02/01',
                    'sal_total' => 377000,
                    'ship_id' => 1,
                    'sal_province' => 'Hồ Chí Minh',
                    'sal_district' => 'Quận 1',
                    'sal_town' => 'Bến Thành',
                    'sal_detailAddress' => 'Nhà 4 ngõ 4 đường Lê Lai',
                    'sal_status_id' => 4,
                ],
                [
                    'use_id' => 6,
                    'sal_date' => '2023/02/03',
                    'sal_total' => 105000,
                    'ship_id' => 1,
                    'sal_province' => 'Hà Nội',
                    'sal_district' => 'Hoàng Mai',
                    'sal_town' => 'Đại Kim',
                    'sal_detailAddress' => 'Số 50 Nguyễn Xiển',
                    'sal_status_id' => 5,
                ],
                [
                    'use_id' => 6,
                    'sal_date' => '2023/03/03',
                    'sal_total' => 840000,
                    'ship_id' => 1,
                    'sal_province' => 'Hà Nội',
                    'sal_district' => 'Hoàng Mai',
                    'sal_town' => 'Đại Kim',
                    'sal_detailAddress' => 'Số 50 Nguyễn Xiển',
                    'sal_status_id' => 4,
                ],
                [
                    'use_id' => 6,
                    'sal_date' => '2023/04/20',
                    'sal_total' => 750000,
                    'ship_id' => 1,
                    'sal_province' => 'Hà Nội',
                    'sal_district' => 'Hoàng Mai',
                    'sal_town' => 'Đại Kim',
                    'sal_detailAddress' => 'Số 50 Nguyễn Xiển',
                    'sal_status_id' => 2,
                ],
                [
                    'use_id' => 5,
                    'sal_date' => '2023/04/20',
                    'sal_total' => 850000,
                    'ship_id' => 1,
                    'sal_province' => 'Hà Nội',
                    'sal_district' => 'Hoàng Mai',
                    'sal_town' => 'Đại Kim',
                    'sal_detailAddress' => 'Số 50 Nguyễn Xiển',
                    'sal_status_id' => 4,
                ],
                [
                    'use_id' => 7,
                    'sal_date' => '2023/05/10',
                    'sal_total' => 1080000,
                    'ship_id' => 1,
                    'sal_province' => 'Hà Nội',
                    'sal_district' => 'Hoàn Kiếm',
                    'sal_town' => 'Hàng Trống',
                    'sal_detailAddress' => 'Số 29 Phố Hàng Trống',
                    'sal_status_id' => 4,
                ],
                [
                    'use_id' => 7,
                    'sal_date' => '2023/06/10',
                    'sal_total' => 960000,
                    'ship_id' => 1,
                    'sal_province' => 'Hà Nội',
                    'sal_district' => 'Hoàn Kiếm',
                    'sal_town' => 'Hàng Trống',
                    'sal_detailAddress' => 'Số 29 Phố Hàng Trống',
                    
                    'sal_status_id' => 4,
                ],
                [
                    'use_id' => 7,
                    'sal_date' => '2023/07/02',
                    'sal_total' => 865000,
                    'ship_id' => 1,
                    'sal_province' => 'Hà Nội',
                    'sal_district' => 'Hoàn Kiếm',
                    'sal_town' => 'Hàng Trống',
                    'sal_detailAddress' => 'Số 29 Phố Hàng Trống',
                    
                    'sal_status_id' => 4,
                ],
                [
                    'use_id' => 6,
                    'sal_date' => '2023/07/10',
                    'sal_total' => 1690000,
                    'ship_id' => 1,
                    'sal_province' => 'Hà Nội',
                    'sal_district' => 'Hoàn Kiếm',
                    'sal_town' => 'Hàng Trống',
                    'sal_detailAddress' => 'Số 10 Phố Hàng Trống',
                    
                    'sal_status_id' => 4,
                ],
                [
                    'use_id' => 6,
                    'sal_date' => '2023/07/11',
                    'sal_total' => 700000,
                    'ship_id' => 1,
                    'sal_province' => 'Hà Nội',
                    'sal_district' => 'Hoàng Mai',
                    'sal_town' => 'Đại Kim',
                    'sal_detailAddress' => 'Số 50 Nguyễn Xiển',
                    'sal_status_id' => 3,
                ],
                [
                    'use_id' => 6,
                    'sal_date' => '2023/07/20',
                    'sal_total' => 240000,
                    'ship_id' => 1,
                    'sal_province' => 'Hà Nội',
                    'sal_district' => 'Hoàng Mai',
                    'sal_town' => 'Đại Kim',
                    'sal_detailAddress' => 'Số 50 Nguyễn Xiển',
                    'sal_status_id' => 2,
                ],
                [
                    'use_id' => 7,
                    'sal_date' => '2023/07/24',
                    'sal_total' => 40000,
                    'ship_id' => 1,
                    'sal_province' => 'Hà Nội',
                    'sal_district' => 'Hoàng Mai',
                    'sal_town' => 'Đại Kim',
                    'sal_detailAddress' => 'Số 12 Ngõ 354 Kim Giang',
                    'sal_status_id' => 1,
                ],
                
            ]
        );
    }
}
